### ISSUE TITLE
Alt attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [IrinaKostevich/codecademy-tea-cozy#3]
Great! I like that you've used descriptive `alt` attributes on your `<img>` elements as this is best practice and helps your site to be even more accessible!

Example: https://github.com/IrinaKostevich/codecademy-tea-cozy/blob/master/src/index.html#L36

For future projects, remember that we can leave `alt` attributes empty (`alt=""`), but should not omit them entirely, when the image does not add information to the content of the page. See this resource to help aid in your decision to give `alt` attribute values (or to leave them empty): https://www.w3.org/WAI/tutorials/images/decorative/

**Comment by IrinaKostevich** [comment]
I agree, that images in this particular project do not add any additional information to the page, so it can be left empty. I’ve fixed that.
