### ISSUE TITLE
Semantic and accessible HTML

### ISSUE THREAD

**Issue by aubreywullschleger** [IrinaKostevich/codecademy-tea-cozy#4]
Great! Great job using semantic HTML elements like `<header>`, `<nav>`, `<main>`, `<section>`, `<address>`, and `<footer>`.  Using semantic elements helps make your HTML more meaningful to browsers reading your markup, helps with SEO, and improves the accessibility of your page. Here's info on how semantic elements help with accessibility: https://webflow.com/blog/html5-semantic-elements-and-webflow-the-essential-guide (scroll down to the 'So what are semantic elements good for?' heading) and a tutorial that goes over semantic elements and more reasons to use semantic HTML: https://internetingishard.com/html-and-css/semantic-html/.

Example: https://github.com/IrinaKostevich/codecademy-tea-cozy/blob/master/src/index.html#L11-L20

Here, try not to skip heading levels for styling purposes - we can always style the headings how we would like in the CSS. For example: lines https://github.com/IrinaKostevich/codecademy-tea-cozy/blob/master/src/index.html#L32-L33 go from `<h2>` to `<h4>`. See here for more info about heading hierarchy and how it relates to accessibility: https://www.w3.org/WAI/tutorials/page-structure/headings/

**Comment by IrinaKostevich** [comment]
I’ve replaced h4 and h5 with p with appropriate style in CSS. Also I’ve read the articles, but the link doesn’t work for me:
https://internetingishard.com/html-and-css/semantic-html/
