### ISSUE TITLE
Nesting elements

### ISSUE THREAD

**Issue by aubreywullschleger** [IrinaKostevich/codecademy-tea-cozy#5]
Subtlety for errors!  When we use a validator to check for errors in the HTML - we see an error: 'The element h5 must not appear as a descendant of the address element.' Instead we should use the the `<a>` element, not wrapped in an `<h5>` for lines 89-91 and something like a `<span>` element for line 92. You can also feel free to not wrap the text at all. Then we'll style the text using CSS instead of default `<h5>` styles. 

https://github.com/IrinaKostevich/codecademy-tea-cozy/blob/master/src/index.html#L89-L92

See more information about the `<address>` element (look specifically at the 'Permitted content' and 'Example' sections): https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

Also, here's the HTML validator I like to use (I copy/paste my code into the text field after choosing 'Text Field' from the dropdown): https://html5.validator.nu/

**Comment by IrinaKostevich** [comment]
I’ve fixed tags, also reviewed the article and bookmarked the HTML validator. I will use it next time for sure!
